///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetTaskModleSchemeSchemeItemsInstruction {
/*
{
  "instructionid": "1397d3cb-fa3e-422d-b0a2-18ce4af66d65",
  "name": "入库直线指令1",
  "roleno": "008",
  "rolename": "办事员",
  "userid": null,
  "userno": null,
  "username": null
} 
*/

  String instructionid;
  String name;
  String roleno;
  String rolename;
  String userid;
  String userno;
  String username;

  GetTaskModleSchemeSchemeItemsInstruction({
    this.instructionid,
    this.name,
    this.roleno,
    this.rolename,
    this.userid,
    this.userno,
    this.username,
  });
  GetTaskModleSchemeSchemeItemsInstruction.fromJson(Map<String, dynamic> json) {
    instructionid = json["instructionid"]?.toString();
    name = json["name"]?.toString();
    roleno = json["roleno"]?.toString();
    rolename = json["rolename"]?.toString();
    userid = json["userid"]?.toString();
    userno = json["userno"]?.toString();
    username = json["username"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["instructionid"] = instructionid;
    data["name"] = name;
    data["roleno"] = roleno;
    data["rolename"] = rolename;
    data["userid"] = userid;
    data["userno"] = userno;
    data["username"] = username;
    return data;
  }
}

class GetTaskModleSchemeSchemeItems {
/*
{
  "schemeItemsid": "8252f3af-47be-42cc-a946-755d9701b4ab",
  "serialNo": 2,
  "taskItemId": "0cda735b-daaf-4425-a71d-84fbb51a0601",
  "matType": "B型",
  "typeCode": "B1",
  "matCode": "B1",
  "matBatch": null,
  "productionDate": 1612396800000,
  "manufacturingDate": 1612396800000,
  "qlevel": "1",
  "remarks": "备注信息",
  "area": "A区",
  "positionNo": "B003-2",
  "ioType": "入库",
  "agvNo": "agv2",
  "instructionTypeId": "1ebd8ae2-e3ad-46ba-ba9e-d270f34425f8",
  "instruction": [
    {
      "instructionid": "1397d3cb-fa3e-422d-b0a2-18ce4af66d65",
      "name": "入库直线指令1",
      "roleno": "008",
      "rolename": "办事员",
      "userid": null,
      "userno": null,
      "username": null
    }
  ]
} 
*/

  String schemeItemsid;
  int serialNo;
  String taskItemId;
  String matType;
  String typeCode;
  String matCode;
  String matBatch;
  int productionDate;
  int manufacturingDate;
  String qlevel;
  String remarks;
  String area;
  String positionNo;
  String ioType;
  String agvNo;
  String instructionTypeId;
  List<GetTaskModleSchemeSchemeItemsInstruction> instruction;

  GetTaskModleSchemeSchemeItems({
    this.schemeItemsid,
    this.serialNo,
    this.taskItemId,
    this.matType,
    this.typeCode,
    this.matCode,
    this.matBatch,
    this.productionDate,
    this.manufacturingDate,
    this.qlevel,
    this.remarks,
    this.area,
    this.positionNo,
    this.ioType,
    this.agvNo,
    this.instructionTypeId,
    this.instruction,
  });
  GetTaskModleSchemeSchemeItems.fromJson(Map<String, dynamic> json) {
    schemeItemsid = json["schemeItemsid"]?.toString();
    serialNo = json["serialNo"]?.toInt();
    taskItemId = json["taskItemId"]?.toString();
    matType = json["matType"]?.toString();
    typeCode = json["typeCode"]?.toString();
    matCode = json["matCode"]?.toString();
    matBatch = json["matBatch"]?.toString();
    productionDate = json["productionDate"]?.toInt();
    manufacturingDate = json["manufacturingDate"]?.toInt();
    qlevel = json["qlevel"]?.toString();
    remarks = json["remarks"]?.toString();
    area = json["area"]?.toString();
    positionNo = json["positionNo"]?.toString();
    ioType = json["ioType"]?.toString();
    agvNo = json["agvNo"]?.toString();
    instructionTypeId = json["instructionTypeId"]?.toString();
    if (json["instruction"] != null) {
      var v = json["instruction"];
      var arr0 = List<GetTaskModleSchemeSchemeItemsInstruction>();
      v.forEach((v) {
        arr0.add(GetTaskModleSchemeSchemeItemsInstruction.fromJson(v));
      });
      instruction = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["schemeItemsid"] = schemeItemsid;
    data["serialNo"] = serialNo;
    data["taskItemId"] = taskItemId;
    data["matType"] = matType;
    data["typeCode"] = typeCode;
    data["matCode"] = matCode;
    data["matBatch"] = matBatch;
    data["productionDate"] = productionDate;
    data["manufacturingDate"] = manufacturingDate;
    data["qlevel"] = qlevel;
    data["remarks"] = remarks;
    data["area"] = area;
    data["positionNo"] = positionNo;
    data["ioType"] = ioType;
    data["agvNo"] = agvNo;
    data["instructionTypeId"] = instructionTypeId;
    if (instruction != null) {
      var v = instruction;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["instruction"] = arr0;
    }
    return data;
  }
}

class GetTaskModleScheme {
/*
{
  "schemeid": "02236a6a-be26-4cd9-90e3-8978d9800bd4",
  "schemeno": "t0001-01",
  "cave": "上洞口",
  "taskNo": "t0001",
  "formulateTime": 1612396800000,
  "formulatePerson": "efb895e3-ace0-4437-ab0e-bd5c950cd155",
  "formulatePersonName": "卢超",
  "checkSign": null,
  "checkPerson": null,
  "checkPersonName": null,
  "checkTime": null,
  "agv1": null,
  "agv2": null,
  "curvefirst": null,
  "status": 0,
  "ioType": "入库",
  "schemeItems": [
    {
      "schemeItemsid": "8252f3af-47be-42cc-a946-755d9701b4ab",
      "serialNo": 2,
      "taskItemId": "0cda735b-daaf-4425-a71d-84fbb51a0601",
      "matType": "B型",
      "typeCode": "B1",
      "matCode": "B1",
      "matBatch": null,
      "productionDate": 1612396800000,
      "manufacturingDate": 1612396800000,
      "qlevel": "1",
      "remarks": "备注信息",
      "area": "A区",
      "positionNo": "B003-2",
      "ioType": "入库",
      "agvNo": "agv2",
      "instructionTypeId": "1ebd8ae2-e3ad-46ba-ba9e-d270f34425f8",
      "instruction": [
        {
          "instructionid": "1397d3cb-fa3e-422d-b0a2-18ce4af66d65",
          "name": "入库直线指令1",
          "roleno": "008",
          "rolename": "办事员",
          "userid": null,
          "userno": null,
          "username": null
        }
      ]
    }
  ]
} 
*/

  String schemeid;
  String schemeno;
  String cave;
  String taskNo;
  int formulateTime;
  String formulatePerson;
  String formulatePersonName;
  String checkSign;
  String checkPerson;
  String checkPersonName;
  String checkTime;
  String agv1;
  String agv2;
  String curvefirst;
  int status;
  String ioType;
  List<GetTaskModleSchemeSchemeItems> schemeItems;

  GetTaskModleScheme({
    this.schemeid,
    this.schemeno,
    this.cave,
    this.taskNo,
    this.formulateTime,
    this.formulatePerson,
    this.formulatePersonName,
    this.checkSign,
    this.checkPerson,
    this.checkPersonName,
    this.checkTime,
    this.agv1,
    this.agv2,
    this.curvefirst,
    this.status,
    this.ioType,
    this.schemeItems,
  });
  GetTaskModleScheme.fromJson(Map<String, dynamic> json) {
    schemeid = json["schemeid"]?.toString();
    schemeno = json["schemeno"]?.toString();
    cave = json["cave"]?.toString();
    taskNo = json["taskNo"]?.toString();
    formulateTime = json["formulateTime"]?.toInt();
    formulatePerson = json["formulatePerson"]?.toString();
    formulatePersonName = json["formulatePersonName"]?.toString();
    checkSign = json["checkSign"]?.toString();
    checkPerson = json["checkPerson"]?.toString();
    checkPersonName = json["checkPersonName"]?.toString();
    checkTime = json["checkTime"]?.toString();
    agv1 = json["agv1"]?.toString();
    agv2 = json["agv2"]?.toString();
    curvefirst = json["curvefirst"]?.toString();
    status = json["status"]?.toInt();
    ioType = json["ioType"]?.toString();
    if (json["schemeItems"] != null) {
      var v = json["schemeItems"];
      var arr0 = List<GetTaskModleSchemeSchemeItems>();
      v.forEach((v) {
        arr0.add(GetTaskModleSchemeSchemeItems.fromJson(v));
      });
      schemeItems = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["schemeid"] = schemeid;
    data["schemeno"] = schemeno;
    data["cave"] = cave;
    data["taskNo"] = taskNo;
    data["formulateTime"] = formulateTime;
    data["formulatePerson"] = formulatePerson;
    data["formulatePersonName"] = formulatePersonName;
    data["checkSign"] = checkSign;
    data["checkPerson"] = checkPerson;
    data["checkPersonName"] = checkPersonName;
    data["checkTime"] = checkTime;
    data["agv1"] = agv1;
    data["agv2"] = agv2;
    data["curvefirst"] = curvefirst;
    data["status"] = status;
    data["ioType"] = ioType;
    if (schemeItems != null) {
      var v = schemeItems;
      var arr0 = List();
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data["schemeItems"] = arr0;
    }
    return data;
  }
}

class GetTaskModle {
/*
{
  "taskid": "5aafd721-c8cd-4d6d-a96c-05aff4a18d80",
  "taskname": "入库保障任务1",
  "taskno": "t0001",
  "type": "入库",
  "state": 3,
  "remarks": null,
  "releaseTime": 1610150400000,
  "startTime": null,
  "scheme": {
    "schemeid": "02236a6a-be26-4cd9-90e3-8978d9800bd4",
    "schemeno": "t0001-01",
    "cave": "上洞口",
    "taskNo": "t0001",
    "formulateTime": 1612396800000,
    "formulatePerson": "efb895e3-ace0-4437-ab0e-bd5c950cd155",
    "formulatePersonName": "卢超",
    "checkSign": null,
    "checkPerson": null,
    "checkPersonName": null,
    "checkTime": null,
    "agv1": null,
    "agv2": null,
    "curvefirst": null,
    "status": 0,
    "ioType": "入库",
    "schemeItems": [
      {
        "schemeItemsid": "8252f3af-47be-42cc-a946-755d9701b4ab",
        "serialNo": 2,
        "taskItemId": "0cda735b-daaf-4425-a71d-84fbb51a0601",
        "matType": "B型",
        "typeCode": "B1",
        "matCode": "B1",
        "matBatch": null,
        "productionDate": 1612396800000,
        "manufacturingDate": 1612396800000,
        "qlevel": "1",
        "remarks": "备注信息",
        "area": "A区",
        "positionNo": "B003-2",
        "ioType": "入库",
        "agvNo": "agv2",
        "instructionTypeId": "1ebd8ae2-e3ad-46ba-ba9e-d270f34425f8",
        "instruction": [
          {
            "instructionid": "1397d3cb-fa3e-422d-b0a2-18ce4af66d65",
            "name": "入库直线指令1",
            "roleno": "008",
            "rolename": "办事员",
            "userid": null,
            "userno": null,
            "username": null
          }
        ]
      }
    ]
  }
} 
*/

  String taskid;
  String taskname;
  String taskno;
  String type;
  int state;
  String remarks;
  int releaseTime;
  String startTime;
  GetTaskModleScheme scheme;

  GetTaskModle({
    this.taskid,
    this.taskname,
    this.taskno,
    this.type,
    this.state,
    this.remarks,
    this.releaseTime,
    this.startTime,
    this.scheme,
  });
  GetTaskModle.fromJson(Map<String, dynamic> json) {
    taskid = json["taskid"]?.toString();
    taskname = json["taskname"]?.toString();
    taskno = json["taskno"]?.toString();
    type = json["type"]?.toString();
    state = json["state"]?.toInt();
    remarks = json["remarks"]?.toString();
    releaseTime = json["releaseTime"]?.toInt();
    startTime = json["startTime"]?.toString();
    scheme = (json["scheme"] != null)
        ? GetTaskModleScheme.fromJson(json["scheme"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["taskid"] = taskid;
    data["taskname"] = taskname;
    data["taskno"] = taskno;
    data["type"] = type;
    data["state"] = state;
    data["remarks"] = remarks;
    data["releaseTime"] = releaseTime;
    data["startTime"] = startTime;
    if (scheme != null) {
      data["scheme"] = scheme.toJson();
    }
    return data;
  }
}
