///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MatQrCodeEntity {
/*
{
  "name": "A型",
  "matcode": "A110",
  "packMaterial": null,
  "boxLength": 6000,
  "boxWidth": null,
  "boxHeight": null,
  "quantity": 3,
  "unit": null
} 
*/

  String name;
  String matcode;
  String packMaterial;
  int boxLength;
  String boxWidth;
  String boxHeight;
  int quantity;
  String unit;

  MatQrCodeEntity({
    this.name,
    this.matcode,
    this.packMaterial,
    this.boxLength,
    this.boxWidth,
    this.boxHeight,
    this.quantity,
    this.unit,
  });
  MatQrCodeEntity.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    matcode = json["matcode"]?.toString();
    packMaterial = json["packMaterial"]?.toString();
    boxLength = json["boxLength"]?.toInt();
    boxWidth = json["boxWidth"]?.toString();
    boxHeight = json["boxHeight"]?.toString();
    quantity = json["quantity"]?.toInt();
    unit = json["unit"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["matcode"] = matcode;
    data["packMaterial"] = packMaterial;
    data["boxLength"] = boxLength;
    data["boxWidth"] = boxWidth;
    data["boxHeight"] = boxHeight;
    data["quantity"] = quantity;
    data["unit"] = unit;
    return data;
  }
}
