///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MatCodeModel {
/*
{
  "id": "1",
  "no": "A01",
  "name": "A型",
  "packMaterial": null,
  "boxLength": 6000,
  "boxWidth": null,
  "boxHeight": null,
  "unit": null,
  "quantity": 3,
  "weight": null,
  "layerLimit": null,
  "type": null,
  "messageNo": null,
  "length": null,
  "wingSpan": null,
  "rudderSpan": null,
  "direction": null,
  "expriryDate": null,
  "maxPressTime": null,
  "maxPowerDuration": null,
  "maxPowerTime": null,
  "checkedPressTime": null,
  "checkedPowerDuration": null,
  "checkedPowerTime": null
} 
*/

  String id;
  String no;
  String name;
  String packMaterial;
  int boxLength;
  String boxWidth;
  String boxHeight;
  String unit;
  int quantity;
  String weight;
  String layerLimit;
  String type;
  String messageNo;
  String length;
  String wingSpan;
  String rudderSpan;
  String direction;
  String expriryDate;
  String maxPressTime;
  String maxPowerDuration;
  String maxPowerTime;
  String checkedPressTime;
  String checkedPowerDuration;
  String checkedPowerTime;

  MatCodeModel({
    this.id,
    this.no,
    this.name,
    this.packMaterial,
    this.boxLength,
    this.boxWidth,
    this.boxHeight,
    this.unit,
    this.quantity,
    this.weight,
    this.layerLimit,
    this.type,
    this.messageNo,
    this.length,
    this.wingSpan,
    this.rudderSpan,
    this.direction,
    this.expriryDate,
    this.maxPressTime,
    this.maxPowerDuration,
    this.maxPowerTime,
    this.checkedPressTime,
    this.checkedPowerDuration,
    this.checkedPowerTime,
  });
  MatCodeModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    no = json["no"]?.toString();
    name = json["name"]?.toString();
    packMaterial = json["packMaterial"]?.toString();
    boxLength = json["boxLength"]?.toInt();
    boxWidth = json["boxWidth"]?.toString();
    boxHeight = json["boxHeight"]?.toString();
    unit = json["unit"]?.toString();
    quantity = json["quantity"]?.toInt();
    weight = json["weight"]?.toString();
    layerLimit = json["layerLimit"]?.toString();
    type = json["type"]?.toString();
    messageNo = json["messageNo"]?.toString();
    length = json["length"]?.toString();
    wingSpan = json["wingSpan"]?.toString();
    rudderSpan = json["rudderSpan"]?.toString();
    direction = json["direction"]?.toString();
    expriryDate = json["expriryDate"]?.toString();
    maxPressTime = json["maxPressTime"]?.toString();
    maxPowerDuration = json["maxPowerDuration"]?.toString();
    maxPowerTime = json["maxPowerTime"]?.toString();
    checkedPressTime = json["checkedPressTime"]?.toString();
    checkedPowerDuration = json["checkedPowerDuration"]?.toString();
    checkedPowerTime = json["checkedPowerTime"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["no"] = no;
    data["name"] = name;
    data["packMaterial"] = packMaterial;
    data["boxLength"] = boxLength;
    data["boxWidth"] = boxWidth;
    data["boxHeight"] = boxHeight;
    data["unit"] = unit;
    data["quantity"] = quantity;
    data["weight"] = weight;
    data["layerLimit"] = layerLimit;
    data["type"] = type;
    data["messageNo"] = messageNo;
    data["length"] = length;
    data["wingSpan"] = wingSpan;
    data["rudderSpan"] = rudderSpan;
    data["direction"] = direction;
    data["expriryDate"] = expriryDate;
    data["maxPressTime"] = maxPressTime;
    data["maxPowerDuration"] = maxPowerDuration;
    data["maxPowerTime"] = maxPowerTime;
    data["checkedPressTime"] = checkedPressTime;
    data["checkedPowerDuration"] = checkedPowerDuration;
    data["checkedPowerTime"] = checkedPowerTime;
    return data;
  }

  static List<MatCodeModel> fromJsonList(List list) {
    if (list == null) return null;
    return list.map((item) => MatCodeModel.fromJson(item)).toList();
  }

  ///custom comparing function to check if two users are equal
  bool isEqual(MatCodeModel model) {
    return this?.id == model?.id;
  }
}
