///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QualityLevelModel {
/*
{
  "name": "新品",
  "value": "新品"
} 
*/

  String name;
  String value;

  QualityLevelModel({
    this.name,
    this.value,
  });
  QualityLevelModel.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    value = json["value"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["value"] = value;
    return data;
  }

  ///custom comparing function to check if two users are equal
  bool isEqual(QualityLevelModel model) {
    return this?.name == model?.name;
  }
}
