///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StockInfoModel {
/*
{
  "id": "1c2c0ce0-3dd7-11eb-a1be-525400123456",
  "code": "A003-1",
  "type": "垛位",
  "matType": "A型",
  "matTypeCode": null,
  "area": "A区",
  "layer": 1,
  "x": 6000,
  "y": 1,
  "length": 6000,
  "status": 2
} 
*/

  String id;
  String code;
  String type;
  String matType;
  String matTypeCode;
  String area;
  int layer;
  int x;
  int y;
  int length;
  int status;

  StockInfoModel({
    this.id,
    this.code,
    this.type,
    this.matType,
    this.matTypeCode,
    this.area,
    this.layer,
    this.x,
    this.y,
    this.length,
    this.status,
  });
  StockInfoModel.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    code = json["code"]?.toString();
    type = json["type"]?.toString();
    matType = json["matType"]?.toString();
    matTypeCode = json["matTypeCode"]?.toString();
    area = json["area"]?.toString();
    layer = json["layer"]?.toInt();
    x = json["x"]?.toInt();
    y = json["y"]?.toInt();
    length = json["length"]?.toInt();
    status = json["status"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["code"] = code;
    data["type"] = type;
    data["matType"] = matType;
    data["matTypeCode"] = matTypeCode;
    data["area"] = area;
    data["layer"] = layer;
    data["x"] = x;
    data["y"] = y;
    data["length"] = length;
    data["status"] = status;
    return data;
  }

  static List<StockInfoModel> fromJsonList(List list) {
    if (list == null) return null;
    return list.map((item) => StockInfoModel.fromJson(item)).toList();
  }

  ///custom comparing function to check if two users are equal
  bool isEqual(StockInfoModel model) {
    return this?.id == model?.id;
  }
}
